// Main validation exports for the backend

// Export all entity validations
export * from './entities';
// Re-export commonly used validators for convenience
export {
  type ApplicationSchema,
  type ApplicationStatus,
  type ChatMessageSchema,
  type ChatSessionSchema,
  type CoverletterSchema,
  type CreateApplicationSchema,
  type CreateChatMessageSchema,
  type CreateChatSessionSchema,
  type CreateCoverletterSchema,
  type CreateCredentialAccountSchema,
  type CreateEmailVerificationSchema,
  type CreateOAuthAccountSchema,
  type CreateResumeSchema,
  type CreateSessionSchema,
  type CreateUserSchema,
  calculateExpiryTime,
  calculateSessionExpiry,
  generateVerificationCode,
  isAccountActive,
  isApplicationActive,
  isSessionExpired,
  isSessionValid,
  isUserActive,
  isValidApplication,
  isValidChatMessage,
  isValidChatSession,
  isValidCoverletter,
  isValidResourceType,
  isValidResume,
  isValidSession,
  isValidStatusTransition,
  isValidUser,
  isValidUserAccount,
  isValidUserVerification,
  isVerificationValid,
  type Platform,
  type ProviderId,
  type ResourceType,
  type ResumeSchema,
  type Sender,
  type SessionSchema,
  sanitizeMessageContent,
  type UpdateApplicationSchema,
  type UpdateCoverletterSchema,
  type UpdateResumeSchema,
  type UpdateUserSchema,
  type UserAccountSchema,
  type UserSchema,
  type UserVerificationSchema,
  type VerifyCodeSchema,
  // Application validations
  validateApplication,
  validateApplicationId,
  validateBulkChatMessages,
  // Chat message validations
  validateChatMessage,
  // Chat session validations
  validateChatSession,
  validateChatSessionId,
  // Coverletter validations
  validateCoverletter,
  validateCoverletterFile,
  validateCoverletterId,
  validateCreateApplication,
  validateCreateChatMessage,
  validateCreateChatSession,
  validateCreateCoverletter,
  validateCreateCredentialAccount,
  validateCreateEmailVerification,
  validateCreateOAuthAccount,
  validateCreateResume,
  validateCreateSession,
  validateCreateUser,
  validateMessageContent,
  validatePasswordStrength,
  validateResendVerification,
  // Resume validations
  validateResume,
  validateResumeFile,
  validateResumeId,
  // Session validations
  validateSession,
  validateSessionId,
  validateSessionIsValid,
  validateUpdateApplication,
  validateUpdateApplicationStatus,
  validateUpdateChatSession,
  validateUpdateCoverletter,
  validateUpdatePassword,
  validateUpdateResume,
  validateUpdateSession,
  validateUpdateUser,
  validateUpdateUserAccount,
  // User validations
  validateUser,
  // User account validations
  validateUserAccount,
  validateUserId,
  validateUserIsActive,
  // User verification validations
  validateUserVerification,
  validateVerifyCode,
} from './entities';
// Export session validations
export * from './sessions/isSessionValid';
